// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "htiop_endpointsC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Sequence_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/AnyTypeCode/Struct_TypeCode_Static.h"
#include "tao/AnyTypeCode/TypeCode_Struct_Field.h"
#include "tao/CDR.h"

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\struct_typecode.cpp:86

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_HTIOP_Endpoint_Info[] =
      {
        { "host", &CORBA::_tc_string },
        { "port", &CORBA::_tc_short },
        { "htid", &CORBA::_tc_string }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_HTIOP_Endpoint_Info (
  ::CORBA::tk_struct,
  "IDL:HTIOP_Endpoint_Info:1.0",
  "HTIOP_Endpoint_Info",
  _tao_fields_HTIOP_Endpoint_Info,
  3);

::CORBA::TypeCode_ptr const _tc_HTIOP_Endpoint_Info =
  &_tao_tc_HTIOP_Endpoint_Info;

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_cs.cpp:105

#if !defined (_HTIOPENDPOINTSEQUENCE_CS_)
#define _HTIOPENDPOINTSEQUENCE_CS_

HTIOPEndpointSequence::HTIOPEndpointSequence (void)
{}

HTIOPEndpointSequence::HTIOPEndpointSequence (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence< HTIOP_Endpoint_Info> (max)
{}

HTIOPEndpointSequence::HTIOPEndpointSequence (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    HTIOP_Endpoint_Info * buffer,
    ::CORBA::Boolean release)
  : ::TAO::unbounded_value_sequence< HTIOP_Endpoint_Info>
    (max, length, buffer, release)
{}

HTIOPEndpointSequence::HTIOPEndpointSequence (
    const HTIOPEndpointSequence &seq)
  : ::TAO::unbounded_value_sequence< HTIOP_Endpoint_Info> (seq)
{}

HTIOPEndpointSequence::~HTIOPEndpointSequence (void)
{}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\alias_typecode.cpp:49



// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_defn.cpp:461


#ifndef _TAO_TYPECODE_HTIOPEndpointSequence_GUARD
#define _TAO_TYPECODE_HTIOPEndpointSequence_GUARD


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace TAO
{
  namespace TypeCode
  {
    namespace
    {
      TAO::TypeCode::Sequence< ::CORBA::TypeCode_ptr const *,
                              TAO::Null_RefCount_Policy>
        HTIOPEndpointSequence_0 (
          ::CORBA::tk_sequence,
          &_tc_HTIOP_Endpoint_Info,
          0U);
        
      ::CORBA::TypeCode_ptr const tc_HTIOPEndpointSequence_0 =
        &HTIOPEndpointSequence_0;
    }
  }
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


#endif /* _TAO_TYPECODE_HTIOPEndpointSequence_GUARD */

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_HTIOPEndpointSequence (
    ::CORBA::tk_alias,
    "IDL:HTIOPEndpointSequence:1.0",
    "HTIOPEndpointSequence",
    &TAO::TypeCode::tc_HTIOPEndpointSequence_0);
  
::CORBA::TypeCode_ptr const _tc_HTIOPEndpointSequence =
  &_tao_tc_HTIOPEndpointSequence;

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const HTIOP_Endpoint_Info &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.host.in ()) &&
    (strm << _tao_aggregate.port) &&
    (strm << _tao_aggregate.htid.in ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    HTIOP_Endpoint_Info &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.host.out ()) &&
    (strm >> _tao_aggregate.port) &&
    (strm >> _tao_aggregate.htid.out ());
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\cdr_op_cs.cpp:93
#if !defined _TAO_CDR_OP_HTIOPEndpointSequence_CPP_
#define _TAO_CDR_OP_HTIOPEndpointSequence_CPP_


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const HTIOPEndpointSequence &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    HTIOPEndpointSequence &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


#endif /* _TAO_CDR_OP_HTIOPEndpointSequence_CPP_ */


TAO_END_VERSIONED_NAMESPACE_DECL


