// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:149

#ifndef _TAO_IDL_RTECUDPADMINC_LDUBTM_H_
#define _TAO_IDL_RTECUDPADMINC_LDUBTM_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "orbsvcs/Event/event_export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/AnyTypeCode/OctetSeqA.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/VarOut_T.h"
#include "tao/Array_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/Fixed_Array_Argument_T.h"
#include "tao/Var_Array_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "RtecEventCommC.h"
#include "tao/OctetSeqC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_root\root_ch.cpp:157

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:35

namespace RtecUDPAdmin
{

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_type.cpp:258

  struct UDP_Addr;

  typedef
    ::TAO_Fixed_Var_T<
        UDP_Addr
      >
    UDP_Addr_var;

  typedef
    UDP_Addr &
    UDP_Addr_out;

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_structure\structure_ch.cpp:48

  struct TAO_RTEvent_Export UDP_Addr
  {

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    
    typedef UDP_Addr_var _var_type;
    typedef UDP_Addr_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::ULong ipaddr;
    ::CORBA::UShort port;
  };

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:34

  extern TAO_RTEvent_Export ::CORBA::TypeCode_ptr const _tc_UDP_Addr;

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_array\array_ch.cpp:52

  typedef ::CORBA::Char char16[16];
  typedef ::CORBA::Char char16_slice;
  struct char16_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        char16,
        char16_slice,
        char16_tag
      >
    char16_var;

  typedef
    char16
    char16_out;

  typedef
    TAO_Array_Forany_T<
        char16,
        char16_slice,
        char16_tag
      >
    char16_forany;

  extern TAO_RTEvent_Export char16_slice *
  char16_alloc (void);

  extern TAO_RTEvent_Export void
  char16_free (
      char16_slice *_tao_slice);
  
  extern TAO_RTEvent_Export char16_slice *
  char16_dup (
      const char16_slice *_tao_slice);
  
  extern TAO_RTEvent_Export void
  char16_copy (
      char16_slice *_tao_to,
      const char16_slice *_tao_from);

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:34

  extern TAO_RTEvent_Export ::CORBA::TypeCode_ptr const _tc_char16;

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_type.cpp:258

  struct UDP_Addr_v6;

  typedef
    ::TAO_Fixed_Var_T<
        UDP_Addr_v6
      >
    UDP_Addr_v6_var;

  typedef
    UDP_Addr_v6 &
    UDP_Addr_v6_out;

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_structure\structure_ch.cpp:48

  struct TAO_RTEvent_Export UDP_Addr_v6
  {

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    
    typedef UDP_Addr_v6_var _var_type;
    typedef UDP_Addr_v6_out _out_type;

    static void _tao_any_destructor (void *);
    
    RtecUDPAdmin::char16 ipaddr;
    ::CORBA::UShort port;
  };

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:34

  extern TAO_RTEvent_Export ::CORBA::TypeCode_ptr const _tc_UDP_Addr_v6;

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_enum\enum_ch.cpp:44

  enum Address_Family
  {
    Rtec_inet,
    Rtec_inet6
  };

  typedef Address_Family &Address_Family_out;

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:34

  extern TAO_RTEvent_Export ::CORBA::TypeCode_ptr const _tc_Address_Family;

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_type.cpp:258

  class UDP_Address;

  typedef
    ::TAO_Fixed_Var_T<
        UDP_Address
      >
    UDP_Address_var;

  typedef
    UDP_Address &
    UDP_Address_out;

  class TAO_RTEvent_Export UDP_Address
  {
  public:
    UDP_Address (void);
    UDP_Address (const UDP_Address &);
    ~UDP_Address (void);

    UDP_Address &operator= (const UDP_Address &);

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_union\discriminant_ch.cpp:67

    void _d (RtecUDPAdmin::Address_Family);
    RtecUDPAdmin::Address_Family _d (void) const;

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    
    typedef UDP_Address_var _var_type;
    typedef UDP_Address_out _out_type;

    static void _tao_any_destructor (void *);

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_union_branch\public_ch.cpp:656

    void v4_addr (const RtecUDPAdmin::UDP_Addr &);
    const RtecUDPAdmin::UDP_Addr &v4_addr (void) const;
    RtecUDPAdmin::UDP_Addr &v4_addr (void);

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_union_branch\public_ch.cpp:656

    void v6_addr (const RtecUDPAdmin::UDP_Addr_v6 &);
    const RtecUDPAdmin::UDP_Addr_v6 &v6_addr (void) const;
    RtecUDPAdmin::UDP_Addr_v6 &v6_addr (void);

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_union\union_ch.cpp:121

    void _default (void);
  private:
    RtecUDPAdmin::Address_Family disc_;

    union
    {
      // TAO_IDL - Generated from
      // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_union_branch\private_ch.cpp:519
      RtecUDPAdmin::UDP_Addr v4_addr_;
      // TAO_IDL - Generated from
      // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_union_branch\private_ch.cpp:519
      RtecUDPAdmin::UDP_Addr_v6 v6_addr_;
    } u_;

    /// TAO extension - frees any allocated storage.
    void _reset (void);
  };

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:34

  extern TAO_RTEvent_Export ::CORBA::TypeCode_ptr const _tc_UDP_Address;

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_RTECUDPADMIN_ADDRSERVER__VAR_OUT_CH_)
#define _RTECUDPADMIN_ADDRSERVER__VAR_OUT_CH_

  class AddrServer;
  typedef AddrServer *AddrServer_ptr;
  typedef TAO_Objref_Var_T<AddrServer> AddrServer_var;
  typedef TAO_Objref_Out_T<AddrServer> AddrServer_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class TAO_RTEvent_Export AddrServer
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<AddrServer>;

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef AddrServer_ptr _ptr_type;
    typedef AddrServer_var _var_type;
    typedef AddrServer_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static AddrServer_ptr _duplicate (AddrServer_ptr obj);

    static void _tao_release (AddrServer_ptr obj);

    static AddrServer_ptr _narrow (::CORBA::Object_ptr obj);
    static AddrServer_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static AddrServer_ptr _nil (void);

    virtual void get_addr (
      const ::RtecEventComm::EventHeader & header,
      ::RtecUDPAdmin::UDP_Addr_out addr);

    virtual void get_address (
      const ::RtecEventComm::EventHeader & header,
      ::RtecUDPAdmin::UDP_Address_out addr);

    // TAO_IDL - Generated from
    // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    AddrServer (void);

    // Concrete non-local interface only.
    AddrServer (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    AddrServer (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~AddrServer (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    AddrServer (const AddrServer &);

    void operator= (const AddrServer &);
  };

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:34

  extern TAO_RTEvent_Export ::CORBA::TypeCode_ptr const _tc_AddrServer;

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:64

} // module RtecUDPAdmin

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:66


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:945

  template<>
  class Arg_Traits< ::RtecUDPAdmin::UDP_Addr>
    : public
        Fixed_Size_Arg_Traits_T<
            ::RtecUDPAdmin::UDP_Addr,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class Arg_Traits< ::RtecUDPAdmin::char16_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::RtecUDPAdmin::char16_var,
            ::RtecUDPAdmin::char16_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:945

  template<>
  class Arg_Traits< ::RtecUDPAdmin::UDP_Addr_v6>
    : public
        Fixed_Size_Arg_Traits_T<
            ::RtecUDPAdmin::UDP_Addr_v6,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:902

  template<>
  class Arg_Traits< ::RtecUDPAdmin::Address_Family>
    : public
        Basic_Arg_Traits_T<
            ::RtecUDPAdmin::Address_Family,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:1056

  template<>
  class Arg_Traits< ::RtecUDPAdmin::UDP_Address>
    : public
        Fixed_Size_Arg_Traits_T<
            ::RtecUDPAdmin::UDP_Address,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:145

#if !defined (_RTECUDPADMIN_ADDRSERVER__ARG_TRAITS_)
#define _RTECUDPADMIN_ADDRSERVER__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::RtecUDPAdmin::AddrServer>
    : public
        Object_Arg_Traits_T<
            ::RtecUDPAdmin::AddrServer_ptr,
            ::RtecUDPAdmin::AddrServer_var,
            ::RtecUDPAdmin::AddrServer_out,
            TAO::Objref_Traits<RtecUDPAdmin::AddrServer>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:60


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
  template<>
  struct TAO_RTEvent_Export Array_Traits<
      RtecUDPAdmin::char16_forany
    >
  {
    static void free (
        RtecUDPAdmin::char16_slice * _tao_slice);
    static RtecUDPAdmin::char16_slice * dup (
        const RtecUDPAdmin::char16_slice * _tao_slice);
    static void copy (
        RtecUDPAdmin::char16_slice * _tao_to,
        const RtecUDPAdmin::char16_slice * _tao_from);
    static RtecUDPAdmin::char16_slice * alloc (void);
    static void zero (
        RtecUDPAdmin::char16_slice * _tao_slice);
  };

#if !defined (_RTECUDPADMIN_ADDRSERVER__TRAITS_)
#define _RTECUDPADMIN_ADDRSERVER__TRAITS_

  template<>
  struct TAO_RTEvent_Export Objref_Traits< ::RtecUDPAdmin::AddrServer>
  {
    static ::RtecUDPAdmin::AddrServer_ptr duplicate (
        ::RtecUDPAdmin::AddrServer_ptr p);
    static void release (
        ::RtecUDPAdmin::AddrServer_ptr p);
    static ::RtecUDPAdmin::AddrServer_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::RtecUDPAdmin::AddrServer_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_structure\any_op_ch.cpp:42



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace RtecUDPAdmin
{
  TAO_RTEvent_Export void operator<<= (::CORBA::Any &, const ::RtecUDPAdmin::UDP_Addr &); // copying version
  TAO_RTEvent_Export void operator<<= (::CORBA::Any &, ::RtecUDPAdmin::UDP_Addr*); // noncopying version
  TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::RtecUDPAdmin::UDP_Addr *&);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export void operator<<= (::CORBA::Any &, const RtecUDPAdmin::UDP_Addr &); // copying version
TAO_RTEvent_Export void operator<<= (::CORBA::Any &, RtecUDPAdmin::UDP_Addr*); // noncopying version
TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const RtecUDPAdmin::UDP_Addr *&);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_array\any_op_ch.cpp:37



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export void operator<<= (::CORBA::Any &, const RtecUDPAdmin::char16_forany &);
TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, RtecUDPAdmin::char16_forany &);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_structure\any_op_ch.cpp:42



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace RtecUDPAdmin
{
  TAO_RTEvent_Export void operator<<= (::CORBA::Any &, const ::RtecUDPAdmin::UDP_Addr_v6 &); // copying version
  TAO_RTEvent_Export void operator<<= (::CORBA::Any &, ::RtecUDPAdmin::UDP_Addr_v6*); // noncopying version
  TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::RtecUDPAdmin::UDP_Addr_v6 *&);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export void operator<<= (::CORBA::Any &, const RtecUDPAdmin::UDP_Addr_v6 &); // copying version
TAO_RTEvent_Export void operator<<= (::CORBA::Any &, RtecUDPAdmin::UDP_Addr_v6*); // noncopying version
TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const RtecUDPAdmin::UDP_Addr_v6 *&);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_enum\any_op_ch.cpp:36

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace RtecUDPAdmin
{
  

  TAO_RTEvent_Export void operator<<= (::CORBA::Any &, ::RtecUDPAdmin::Address_Family);
  TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::RtecUDPAdmin::Address_Family &);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



TAO_RTEvent_Export void operator<<= (::CORBA::Any &, RtecUDPAdmin::Address_Family);
TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, RtecUDPAdmin::Address_Family &);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_union\any_op_ch.cpp:37



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace RtecUDPAdmin
{
  TAO_RTEvent_Export void operator<<= (::CORBA::Any &, const ::RtecUDPAdmin::UDP_Address &); // copying version
  TAO_RTEvent_Export void operator<<= (::CORBA::Any &, ::RtecUDPAdmin::UDP_Address*); // noncopying version
  TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::RtecUDPAdmin::UDP_Address *&);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export void operator<<= (::CORBA::Any &, const RtecUDPAdmin::UDP_Address &); // copying version
TAO_RTEvent_Export void operator<<= (::CORBA::Any &, RtecUDPAdmin::UDP_Address*); // noncopying version
TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const RtecUDPAdmin::UDP_Address *&);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\any_op_ch.cpp:41



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace RtecUDPAdmin
{
  TAO_RTEvent_Export void operator<<= ( ::CORBA::Any &, AddrServer_ptr); // copying
  TAO_RTEvent_Export void operator<<= ( ::CORBA::Any &, AddrServer_ptr *); // non-copying
  TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, AddrServer_ptr &);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export void operator<<= (::CORBA::Any &, RtecUDPAdmin::AddrServer_ptr); // copying
TAO_RTEvent_Export void operator<<= (::CORBA::Any &, RtecUDPAdmin::AddrServer_ptr *); // non-copying
TAO_RTEvent_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, RtecUDPAdmin::AddrServer_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_ch.cpp:43



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const RtecUDPAdmin::UDP_Addr &);
TAO_RTEvent_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, RtecUDPAdmin::UDP_Addr &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_array\cdr_op_ch.cpp:99



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const RtecUDPAdmin::char16_forany &_tao_array);
TAO_RTEvent_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, RtecUDPAdmin::char16_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_ch.cpp:43



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const RtecUDPAdmin::UDP_Addr_v6 &);
TAO_RTEvent_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, RtecUDPAdmin::UDP_Addr_v6 &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_enum\cdr_op_ch.cpp:34



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, RtecUDPAdmin::Address_Family _tao_enumerator);
TAO_RTEvent_Export ::CORBA::Boolean operator>> (TAO_InputCDR &strm, RtecUDPAdmin::Address_Family &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_union\cdr_op_ch.cpp:38



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const RtecUDPAdmin::UDP_Address &);
TAO_RTEvent_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, RtecUDPAdmin::UDP_Address &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\cdr_op_ch.cpp:41


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_RTEvent_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const RtecUDPAdmin::AddrServer_ptr );
TAO_RTEvent_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, RtecUDPAdmin::AddrServer_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1686


TAO_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "RtecUDPAdminC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

