// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/


// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:635

#ifndef _TAO_IDL_NOTIFY_MONITORCONTROLEXT_NOTIFYMONITORINGEXTS_4B6M5U_CPP_
#define _TAO_IDL_NOTIFY_MONITORCONTROLEXT_NOTIFYMONITORINGEXTS_4B6M5U_CPP_


#include "NotifyMonitoringExtS.h"
#include "tao/PortableServer/Operation_Table_Perfect_Hash.h"
#include "tao/PortableServer/Upcall_Command.h"
#include "tao/PortableServer/Upcall_Wrapper.h"
#include "tao/TAO_Server_Request.h"
#include "tao/ORB_Core.h"
#include "tao/Profile.h"
#include "tao/Stub.h"
#include "tao/IFR_Client_Adapter.h"
#include "tao/Object_T.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/DynamicC.h"
#include "tao/CDR.h"
#include "tao/operation_details.h"
#include "tao/PortableInterceptor.h"
#include "ace/Dynamic_Service.h"
#include "ace/Malloc_Allocator.h"

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_interface.cpp:1863

class TAO_NotifyMonitoringExt_SupplierAdmin_Perfect_Hash_OpTable
  : public TAO_Perfect_Hash_OpTable
{
private:
  unsigned int hash (const char *str, unsigned int len);

public:
  const TAO_operation_db_entry * lookup (const char *str, unsigned int len);
};

/* C++ code produced by gperf version 2.8 (ACE version) */
/* Command-line: ace_gperf -m -M -J -c -C -D -E -T -f 0 -F 0,0 -a -o -t -p -K opname -L C++ -Z TAO_NotifyMonitoringExt_SupplierAdmin_Perfect_Hash_OpTable -N lookup  */
unsigned int
TAO_NotifyMonitoringExt_SupplierAdmin_Perfect_Hash_OpTable::hash (const char *str, unsigned int len)
{
  static const unsigned char asso_values[] =
    {
     43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
     43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
     43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
     43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
     43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
     43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
     43, 43, 43, 43, 43, 43, 43, 43,  0, 43,
     43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
     43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
     43, 43, 43, 43, 43,  0, 43,  1, 43, 43,
      0,  0, 43, 20, 43, 43, 43, 43, 10, 43,
     43,  0, 43, 43,  0,  0, 15, 43,  5, 43,
     43, 15, 43, 43, 43, 43, 43, 43,
    };
  return len + asso_values[static_cast<int>(str[len - 1])] + asso_values[static_cast<int>(str[0])];
}

const TAO_operation_db_entry *
TAO_NotifyMonitoringExt_SupplierAdmin_Perfect_Hash_OpTable::lookup (const char *str, unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 27,
      MIN_WORD_LENGTH = 5,
      MAX_WORD_LENGTH = 42,
      MIN_HASH_VALUE = 6,
      MAX_HASH_VALUE = 42,
      HASH_VALUE_RANGE = 37,
      DUPLICATES = 4,
      WORDLIST_SIZE = 33
    };

  static const TAO_operation_db_entry wordlist[] =
    {
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"_is_a", &TAO_ServantBase::_is_a_thru_poa_skel, 0},
      {"set_qos", &POA_CosNotification::QoSAdmin::set_qos_skel, 0},
      {"_get_MyID", &POA_CosNotifyChannelAdmin::SupplierAdmin::_get_MyID_skel, 0},
      {"_interface", &TAO_ServantBase::_interface_skel, 0},
      {"add_filter", &POA_CosNotifyFilter::FilterAdmin::add_filter_skel, 0},
      {"offer_change", &POA_CosNotifyComm::NotifyPublish::offer_change_skel, 0},
      {"remove_filter", &POA_CosNotifyFilter::FilterAdmin::remove_filter_skel, 0},
      {"_repository_id", &TAO_ServantBase::_repository_id_thru_poa_skel, 0},
      {"_get_MyOperator", &POA_CosNotifyChannelAdmin::SupplierAdmin::_get_MyOperator_skel, 0},
      {"validate_qos", &POA_CosNotification::QoSAdmin::validate_qos_skel, 0},
      {"remove_all_filters", &POA_CosNotifyFilter::FilterAdmin::remove_all_filters_skel, 0},
      {"_get_pull_consumers", &POA_CosNotifyChannelAdmin::SupplierAdmin::_get_pull_consumers_skel, 0},
      {"_get_push_consumers", &POA_CosNotifyChannelAdmin::SupplierAdmin::_get_push_consumers_skel, 0},
      {"obtain_push_consumer", &POA_CosEventChannelAdmin::SupplierAdmin::obtain_push_consumer_skel, 0},
      {"obtain_pull_consumer", &POA_CosEventChannelAdmin::SupplierAdmin::obtain_pull_consumer_skel, 0},
      {"destroy", &POA_CosNotifyChannelAdmin::SupplierAdmin::destroy_skel, 0},
      {"_get_MyChannel", &POA_CosNotifyChannelAdmin::SupplierAdmin::_get_MyChannel_skel, 0},
      {"_component", &TAO_ServantBase::_component_thru_poa_skel, 0},
      {"get_qos", &POA_CosNotification::QoSAdmin::get_qos_skel, 0},
      {"_non_existent", &TAO_ServantBase::_non_existent_thru_poa_skel, 0},
      {"get_filter", &POA_CosNotifyFilter::FilterAdmin::get_filter_skel, 0},
      {"obtain_notification_pull_consumer", &POA_CosNotifyChannelAdmin::SupplierAdmin::obtain_notification_pull_consumer_skel, 0},
      {"obtain_notification_push_consumer", &POA_CosNotifyChannelAdmin::SupplierAdmin::obtain_notification_push_consumer_skel, 0},
      {"get_all_filters", &POA_CosNotifyFilter::FilterAdmin::get_all_filters_skel, 0},
      {"get_proxy_consumer", &POA_CosNotifyChannelAdmin::SupplierAdmin::get_proxy_consumer_skel, 0},
      {"obtain_named_notification_push_consumer", &POA_NotifyMonitoringExt::SupplierAdmin::obtain_named_notification_push_consumer_skel, 0},
      {"obtain_notification_push_consumer_with_qos", &POA_NotifyExt::SupplierAdmin::obtain_notification_push_consumer_with_qos_skel, 0},
    };

  static const signed char lookup[] =
    {
       -1,  -1, -17,  -2, -19,  -2,   6,   7,  -1,   8,   9,  10,  11,  12, 
       13,  14,  -1,  15,  16, -59, -58,  -1,  21,  -1,  22,  23,  -1,  24, 
       25,  -1,  26, -27,  -2, -44,  -1,  29,  -1,  -1,  30,  31,  -1,  -1, 
       32, 
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          int slot = lookup[key];

          if (slot >= 0 && slot < WORDLIST_SIZE)
            {
              const char *s = wordlist[slot].opname;

              if (*str == *s && !ACE_OS::strncmp (str + 1, s + 1, len - 1))
                return &wordlist[slot];
            }
          else if (slot < 0 && slot >= -MAX_HASH_VALUE)
            return 0;
          else
            {
              unsigned int offset = key + slot + (slot > 0 ? -MAX_HASH_VALUE : MAX_HASH_VALUE);
              const TAO_operation_db_entry *base = &wordlist[-lookup[offset]];
              const TAO_operation_db_entry *ptr = base + -lookup[offset + 1];

              while (--ptr >= base)
                if (*str == *ptr->opname && !ACE_OS::strncmp (str + 1, ptr->opname + 1, len - 1))
                  return ptr;
            }
        }
    }
  return 0;
}

static TAO_NotifyMonitoringExt_SupplierAdmin_Perfect_Hash_OpTable tao_NotifyMonitoringExt_SupplierAdmin_optable;

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:90

POA_NotifyMonitoringExt::SupplierAdmin::SupplierAdmin (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_NotifyMonitoringExt_SupplierAdmin_optable;
}

POA_NotifyMonitoringExt::SupplierAdmin::SupplierAdmin (const SupplierAdmin& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_CosNotification::QoSAdmin (rhs),
    POA_CosNotifyComm::NotifyPublish (rhs),
    POA_CosNotifyFilter::FilterAdmin (rhs),
    POA_CosEventChannelAdmin::SupplierAdmin (rhs),
    POA_CosNotifyChannelAdmin::SupplierAdmin (rhs),
    POA_NotifyExt::SupplierAdmin (rhs)
{
}

POA_NotifyMonitoringExt::SupplierAdmin::~SupplierAdmin (void)
{
}

namespace POA_NotifyMonitoringExt
{
  

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\upcall_command_ss.cpp:80

  class obtain_named_notification_push_consumer_SupplierAdmin
    : public TAO::Upcall_Command
  {
  public:
    inline obtain_named_notification_push_consumer_SupplierAdmin (
      POA_NotifyMonitoringExt::SupplierAdmin * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::ProxyConsumer>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CosNotifyChannelAdmin::ProxyConsumer> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::ClientType>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CosNotifyChannelAdmin::ClientType> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CORBA::Long>::out_arg_type arg_2 =
        TAO::Portable_Server::get_out_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          2);
        
      TAO::SArg_Traits< char *>::in_arg_type arg_3 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          3);
        
      retval =
        this->servant_->obtain_named_notification_push_consumer (
          arg_1
          , arg_2
          , arg_3);
    }
  
  private:
    POA_NotifyMonitoringExt::SupplierAdmin * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_ss.cpp:168

void POA_NotifyMonitoringExt::SupplierAdmin::obtain_named_notification_push_consumer_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      CosNotifyChannelAdmin::_tc_AdminLimitExceeded,
      NotifyMonitoringExt::_tc_NameAlreadyUsed,
      NotifyMonitoringExt::_tc_NameMapError
    };
  static ::CORBA::ULong const nexceptions = 3;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::CosNotifyChannelAdmin::ProxyConsumer>::ret_val retval;
  TAO::SArg_Traits< ::CosNotifyChannelAdmin::ClientType>::in_arg_val _tao_ctype;
  TAO::SArg_Traits< ::CORBA::Long>::out_arg_val _tao_proxy_id;
  TAO::SArg_Traits< char *>::in_arg_val _tao_name;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_ctype,
      &_tao_proxy_id,
      &_tao_name
    };
  
  static size_t const nargs = 4;

  POA_NotifyMonitoringExt::SupplierAdmin * const impl =
    dynamic_cast<POA_NotifyMonitoringExt::SupplierAdmin *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  obtain_named_notification_push_consumer_SupplierAdmin command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:163



::CORBA::Boolean POA_NotifyMonitoringExt::SupplierAdmin::_is_a (const char* value)
{
  return
    (
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotification/QoSAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyComm/NotifyPublish:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyFilter/FilterAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosEventChannelAdmin/SupplierAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyChannelAdmin/SupplierAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:NotifyExt/SupplierAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:sandia.gov/NotifyMonitoringExt/SupplierAdmin:1.0"
        ) == 0 ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_NotifyMonitoringExt::SupplierAdmin::_interface_repository_id (void) const
{
  return "IDL:sandia.gov/NotifyMonitoringExt/SupplierAdmin:1.0";
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:423

void POA_NotifyMonitoringExt::SupplierAdmin::_dispatch (
  TAO_ServerRequest & req,
  TAO::Portable_Server::Servant_Upcall* servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:370

NotifyMonitoringExt::SupplierAdmin *
POA_NotifyMonitoringExt::SupplierAdmin::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();

  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();

  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0);
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();

  typedef ::NotifyMonitoringExt::SupplierAdmin STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in ());
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_interface.cpp:1863

class TAO_NotifyMonitoringExt_ConsumerAdmin_Perfect_Hash_OpTable
  : public TAO_Perfect_Hash_OpTable
{
private:
  unsigned int hash (const char *str, unsigned int len);

public:
  const TAO_operation_db_entry * lookup (const char *str, unsigned int len);
};

/* C++ code produced by gperf version 2.8 (ACE version) */
/* Command-line: ace_gperf -m -M -J -c -C -D -E -T -f 0 -F 0,0 -a -o -t -p -K opname -L C++ -Z TAO_NotifyMonitoringExt_ConsumerAdmin_Perfect_Hash_OpTable -N lookup  */
unsigned int
TAO_NotifyMonitoringExt_ConsumerAdmin_Perfect_Hash_OpTable::hash (const char *str, unsigned int len)
{
  static const unsigned char asso_values[] =
    {
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48,  0, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48,  0, 48, 18, 48, 48,
      0, 26, 48, 25, 48, 48, 48, 48, 10, 48,
     48,  5, 48, 48,  0,  0, 20, 48,  0, 48,
     48, 10, 48, 48, 48, 48, 48, 48,
    };
  return len + asso_values[static_cast<int>(str[len - 1])] + asso_values[static_cast<int>(str[0])];
}

const TAO_operation_db_entry *
TAO_NotifyMonitoringExt_ConsumerAdmin_Perfect_Hash_OpTable::lookup (const char *str, unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 31,
      MIN_WORD_LENGTH = 5,
      MAX_WORD_LENGTH = 42,
      MIN_HASH_VALUE = 7,
      MAX_HASH_VALUE = 47,
      HASH_VALUE_RANGE = 41,
      DUPLICATES = 7,
      WORDLIST_SIZE = 38
    };

  static const TAO_operation_db_entry wordlist[] =
    {
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"set_qos", &POA_CosNotification::QoSAdmin::set_qos_skel, 0},
      {"_get_MyID", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_get_MyID_skel, 0},
      {"validate_qos", &POA_CosNotification::QoSAdmin::validate_qos_skel, 0},
      {"remove_filter", &POA_CosNotifyFilter::FilterAdmin::remove_filter_skel, 0},
      {"_repository_id", &TAO_ServantBase::_repository_id_thru_poa_skel, 0},
      {"_get_MyOperator", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_get_MyOperator_skel, 0},
      {"destroy", &POA_CosNotifyChannelAdmin::ConsumerAdmin::destroy_skel, 0},
      {"remove_all_filters", &POA_CosNotifyFilter::FilterAdmin::remove_all_filters_skel, 0},
      {"_get_pull_suppliers", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_get_pull_suppliers_skel, 0},
      {"_get_push_suppliers", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_get_push_suppliers_skel, 0},
      {"_get_priority_filter", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_get_priority_filter_skel, 0},
      {"_set_lifetime_filter", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_set_lifetime_filter_skel, 0},
      {"_get_lifetime_filter", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_get_lifetime_filter_skel, 0},
      {"_set_priority_filter", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_set_priority_filter_skel, 0},
      {"_is_a", &TAO_ServantBase::_is_a_thru_poa_skel, 0},
      {"_get_MyChannel", &POA_CosNotifyChannelAdmin::ConsumerAdmin::_get_MyChannel_skel, 0},
      {"obtain_push_supplier", &POA_CosEventChannelAdmin::ConsumerAdmin::obtain_push_supplier_skel, 0},
      {"obtain_pull_supplier", &POA_CosEventChannelAdmin::ConsumerAdmin::obtain_pull_supplier_skel, 0},
      {"add_filter", &POA_CosNotifyFilter::FilterAdmin::add_filter_skel, 0},
      {"_component", &TAO_ServantBase::_component_thru_poa_skel, 0},
      {"get_qos", &POA_CosNotification::QoSAdmin::get_qos_skel, 0},
      {"_non_existent", &TAO_ServantBase::_non_existent_thru_poa_skel, 0},
      {"get_filter", &POA_CosNotifyFilter::FilterAdmin::get_filter_skel, 0},
      {"_interface", &TAO_ServantBase::_interface_skel, 0},
      {"obtain_notification_pull_supplier", &POA_CosNotifyChannelAdmin::ConsumerAdmin::obtain_notification_pull_supplier_skel, 0},
      {"obtain_notification_push_supplier", &POA_CosNotifyChannelAdmin::ConsumerAdmin::obtain_notification_push_supplier_skel, 0},
      {"get_all_filters", &POA_CosNotifyFilter::FilterAdmin::get_all_filters_skel, 0},
      {"get_proxy_supplier", &POA_CosNotifyChannelAdmin::ConsumerAdmin::get_proxy_supplier_skel, 0},
      {"obtain_named_notification_push_supplier", &POA_NotifyMonitoringExt::ConsumerAdmin::obtain_named_notification_push_supplier_skel, 0},
      {"subscription_change", &POA_CosNotifyComm::NotifySubscribe::subscription_change_skel, 0},
      {"obtain_notification_push_supplier_with_qos", &POA_NotifyExt::ConsumerAdmin::obtain_notification_push_supplier_with_qos_skel, 0},
    };

  static const signed char lookup[] =
    {
       -1,  -1,  -1,  -1,  -1, -15,  -2,   7,  -1,   8, -17,  -4,   9,  10, 
       11,  12,  -1,  13,  14, -61, -57, -23,  -2,  21,  22, -51, -31,  -2, 
       25,  -1,  26,  -1,  27,  28,  -1,  29,  30,  -1, -59,  -1,  33,  -1, 
       -1,  34,  35,  36,  -1,  37, 
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          int slot = lookup[key];

          if (slot >= 0 && slot < WORDLIST_SIZE)
            {
              const char *s = wordlist[slot].opname;

              if (*str == *s && !ACE_OS::strncmp (str + 1, s + 1, len - 1))
                return &wordlist[slot];
            }
          else if (slot < 0 && slot >= -MAX_HASH_VALUE)
            return 0;
          else
            {
              unsigned int offset = key + slot + (slot > 0 ? -MAX_HASH_VALUE : MAX_HASH_VALUE);
              const TAO_operation_db_entry *base = &wordlist[-lookup[offset]];
              const TAO_operation_db_entry *ptr = base + -lookup[offset + 1];

              while (--ptr >= base)
                if (*str == *ptr->opname && !ACE_OS::strncmp (str + 1, ptr->opname + 1, len - 1))
                  return ptr;
            }
        }
    }
  return 0;
}

static TAO_NotifyMonitoringExt_ConsumerAdmin_Perfect_Hash_OpTable tao_NotifyMonitoringExt_ConsumerAdmin_optable;

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:90

POA_NotifyMonitoringExt::ConsumerAdmin::ConsumerAdmin (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_NotifyMonitoringExt_ConsumerAdmin_optable;
}

POA_NotifyMonitoringExt::ConsumerAdmin::ConsumerAdmin (const ConsumerAdmin& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_CosNotification::QoSAdmin (rhs),
    POA_CosNotifyComm::NotifySubscribe (rhs),
    POA_CosNotifyFilter::FilterAdmin (rhs),
    POA_CosEventChannelAdmin::ConsumerAdmin (rhs),
    POA_CosNotifyChannelAdmin::ConsumerAdmin (rhs),
    POA_NotifyExt::ConsumerAdmin (rhs)
{
}

POA_NotifyMonitoringExt::ConsumerAdmin::~ConsumerAdmin (void)
{
}

namespace POA_NotifyMonitoringExt
{
  

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\upcall_command_ss.cpp:80

  class obtain_named_notification_push_supplier_ConsumerAdmin
    : public TAO::Upcall_Command
  {
  public:
    inline obtain_named_notification_push_supplier_ConsumerAdmin (
      POA_NotifyMonitoringExt::ConsumerAdmin * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::ProxySupplier>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CosNotifyChannelAdmin::ProxySupplier> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::ClientType>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CosNotifyChannelAdmin::ClientType> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CORBA::Long>::out_arg_type arg_2 =
        TAO::Portable_Server::get_out_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          2);
        
      TAO::SArg_Traits< char *>::in_arg_type arg_3 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          3);
        
      retval =
        this->servant_->obtain_named_notification_push_supplier (
          arg_1
          , arg_2
          , arg_3);
    }
  
  private:
    POA_NotifyMonitoringExt::ConsumerAdmin * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_ss.cpp:168

void POA_NotifyMonitoringExt::ConsumerAdmin::obtain_named_notification_push_supplier_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      CosNotifyChannelAdmin::_tc_AdminLimitExceeded,
      NotifyMonitoringExt::_tc_NameAlreadyUsed,
      NotifyMonitoringExt::_tc_NameMapError
    };
  static ::CORBA::ULong const nexceptions = 3;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::CosNotifyChannelAdmin::ProxySupplier>::ret_val retval;
  TAO::SArg_Traits< ::CosNotifyChannelAdmin::ClientType>::in_arg_val _tao_ctype;
  TAO::SArg_Traits< ::CORBA::Long>::out_arg_val _tao_proxy_id;
  TAO::SArg_Traits< char *>::in_arg_val _tao_name;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_ctype,
      &_tao_proxy_id,
      &_tao_name
    };
  
  static size_t const nargs = 4;

  POA_NotifyMonitoringExt::ConsumerAdmin * const impl =
    dynamic_cast<POA_NotifyMonitoringExt::ConsumerAdmin *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  obtain_named_notification_push_supplier_ConsumerAdmin command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:163



::CORBA::Boolean POA_NotifyMonitoringExt::ConsumerAdmin::_is_a (const char* value)
{
  return
    (
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotification/QoSAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyComm/NotifySubscribe:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyFilter/FilterAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosEventChannelAdmin/ConsumerAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyChannelAdmin/ConsumerAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:NotifyExt/ConsumerAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:sandia.gov/NotifyMonitoringExt/ConsumerAdmin:1.0"
        ) == 0 ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_NotifyMonitoringExt::ConsumerAdmin::_interface_repository_id (void) const
{
  return "IDL:sandia.gov/NotifyMonitoringExt/ConsumerAdmin:1.0";
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:423

void POA_NotifyMonitoringExt::ConsumerAdmin::_dispatch (
  TAO_ServerRequest & req,
  TAO::Portable_Server::Servant_Upcall* servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:370

NotifyMonitoringExt::ConsumerAdmin *
POA_NotifyMonitoringExt::ConsumerAdmin::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();

  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();

  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0);
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();

  typedef ::NotifyMonitoringExt::ConsumerAdmin STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in ());
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_interface.cpp:1863

class TAO_NotifyMonitoringExt_EventChannel_Perfect_Hash_OpTable
  : public TAO_Perfect_Hash_OpTable
{
private:
  unsigned int hash (const char *str, unsigned int len);

public:
  const TAO_operation_db_entry * lookup (const char *str, unsigned int len);
};

/* C++ code produced by gperf version 2.8 (ACE version) */
/* Command-line: ace_gperf -m -M -J -c -C -D -E -T -f 0 -F 0,0 -a -o -t -p -K opname -L C++ -Z TAO_NotifyMonitoringExt_EventChannel_Perfect_Hash_OpTable -N lookup  */
unsigned int
TAO_NotifyMonitoringExt_EventChannel_Perfect_Hash_OpTable::hash (const char *str, unsigned int len)
{
  static const unsigned char asso_values[] =
    {
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
     48, 48, 48, 48, 48,  0, 48,  0, 48, 48,
     25,  5,  5, 15, 48, 48, 48, 48, 48, 48,
      0, 48, 48, 48, 48,  0,  0, 48,  0, 48,
     48, 15, 48, 48, 48, 48, 48, 48,
    };
  return len + asso_values[static_cast<int>(str[len - 1])] + asso_values[static_cast<int>(str[0])];
}

const TAO_operation_db_entry *
TAO_NotifyMonitoringExt_EventChannel_Perfect_Hash_OpTable::lookup (const char *str, unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 25,
      MIN_WORD_LENGTH = 5,
      MAX_WORD_LENGTH = 27,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 47,
      HASH_VALUE_RANGE = 43,
      DUPLICATES = 7,
      WORDLIST_SIZE = 30
    };

  static const TAO_operation_db_entry wordlist[] =
    {
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"_is_a", &TAO_ServantBase::_is_a_thru_poa_skel, 0},
      {"set_qos", &POA_CosNotification::QoSAdmin::set_qos_skel, 0},
      {"set_admin", &POA_CosNotification::AdminPropertiesAdmin::set_admin_skel, 0},
      {"_component", &TAO_ServantBase::_component_thru_poa_skel, 0},
      {"validate_qos", &POA_CosNotification::QoSAdmin::validate_qos_skel, 0},
      {"_non_existent", &TAO_ServantBase::_non_existent_thru_poa_skel, 0},
      {"_interface", &TAO_ServantBase::_interface_skel, 0},
      {"new_for_consumers", &POA_CosNotifyChannelAdmin::EventChannel::new_for_consumers_skel, 0},
      {"new_for_suppliers", &POA_CosNotifyChannelAdmin::EventChannel::new_for_suppliers_skel, 0},
      {"for_consumers", &POA_CosEventChannelAdmin::EventChannel::for_consumers_skel, 0},
      {"for_suppliers", &POA_CosEventChannelAdmin::EventChannel::for_suppliers_skel, 0},
      {"get_qos", &POA_CosNotification::QoSAdmin::get_qos_skel, 0},
      {"named_new_for_consumers", &POA_NotifyMonitoringExt::EventChannel::named_new_for_consumers_skel, 0},
      {"named_new_for_suppliers", &POA_NotifyMonitoringExt::EventChannel::named_new_for_suppliers_skel, 0},
      {"get_admin", &POA_CosNotification::AdminPropertiesAdmin::get_admin_skel, 0},
      {"_get_default_consumer_admin", &POA_CosNotifyChannelAdmin::EventChannel::_get_default_consumer_admin_skel, 0},
      {"_get_default_supplier_admin", &POA_CosNotifyChannelAdmin::EventChannel::_get_default_supplier_admin_skel, 0},
      {"_get_MyFactory", &POA_CosNotifyChannelAdmin::EventChannel::_get_MyFactory_skel, 0},
      {"get_consumeradmin", &POA_CosNotifyChannelAdmin::EventChannel::get_consumeradmin_skel, 0},
      {"get_supplieradmin", &POA_CosNotifyChannelAdmin::EventChannel::get_supplieradmin_skel, 0},
      {"get_all_consumeradmins", &POA_CosNotifyChannelAdmin::EventChannel::get_all_consumeradmins_skel, 0},
      {"get_all_supplieradmins", &POA_CosNotifyChannelAdmin::EventChannel::get_all_supplieradmins_skel, 0},
      {"_repository_id", &TAO_ServantBase::_repository_id_thru_poa_skel, 0},
      {"_get_default_filter_factory", &POA_CosNotifyChannelAdmin::EventChannel::_get_default_filter_factory_skel, 0},
      {"destroy", &POA_CosEventChannelAdmin::EventChannel::destroy_skel, 0},
    };

  static const signed char lookup[] =
    {
       -1, -12,  -2, -14,  -2,   5,  -1,   6,  -1,   7,   8,  -1,   9,  10, 
       -1,  11,  -1, -63, -62,  -1, -17,  -2,  16, -50,  19, -20,  -2, -49, 
       -1,  22, -23,  -2, -49,  -1,  -1, -25,  -2, -49,  -1,  27,  -1,  -1, 
       28,  -1,  -1,  -1,  -1,  29, 
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          int slot = lookup[key];

          if (slot >= 0 && slot < WORDLIST_SIZE)
            {
              const char *s = wordlist[slot].opname;

              if (*str == *s && !ACE_OS::strncmp (str + 1, s + 1, len - 1))
                return &wordlist[slot];
            }
          else if (slot < 0 && slot >= -MAX_HASH_VALUE)
            return 0;
          else
            {
              unsigned int offset = key + slot + (slot > 0 ? -MAX_HASH_VALUE : MAX_HASH_VALUE);
              const TAO_operation_db_entry *base = &wordlist[-lookup[offset]];
              const TAO_operation_db_entry *ptr = base + -lookup[offset + 1];

              while (--ptr >= base)
                if (*str == *ptr->opname && !ACE_OS::strncmp (str + 1, ptr->opname + 1, len - 1))
                  return ptr;
            }
        }
    }
  return 0;
}

static TAO_NotifyMonitoringExt_EventChannel_Perfect_Hash_OpTable tao_NotifyMonitoringExt_EventChannel_optable;

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:90

POA_NotifyMonitoringExt::EventChannel::EventChannel (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_NotifyMonitoringExt_EventChannel_optable;
}

POA_NotifyMonitoringExt::EventChannel::EventChannel (const EventChannel& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_CosNotification::QoSAdmin (rhs),
    POA_CosNotification::AdminPropertiesAdmin (rhs),
    POA_CosEventChannelAdmin::EventChannel (rhs),
    POA_CosNotifyChannelAdmin::EventChannel (rhs)
{
}

POA_NotifyMonitoringExt::EventChannel::~EventChannel (void)
{
}

namespace POA_NotifyMonitoringExt
{
  

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\upcall_command_ss.cpp:80

  class named_new_for_consumers_EventChannel
    : public TAO::Upcall_Command
  {
  public:
    inline named_new_for_consumers_EventChannel (
      POA_NotifyMonitoringExt::EventChannel * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::ConsumerAdmin>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CosNotifyChannelAdmin::ConsumerAdmin> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::InterFilterGroupOperator>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CosNotifyChannelAdmin::InterFilterGroupOperator> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CORBA::Long>::out_arg_type arg_2 =
        TAO::Portable_Server::get_out_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          2);
        
      TAO::SArg_Traits< char *>::in_arg_type arg_3 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          3);
        
      retval =
        this->servant_->named_new_for_consumers (
          arg_1
          , arg_2
          , arg_3);
    }
  
  private:
    POA_NotifyMonitoringExt::EventChannel * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_ss.cpp:168

void POA_NotifyMonitoringExt::EventChannel::named_new_for_consumers_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      NotifyMonitoringExt::_tc_NameAlreadyUsed,
      NotifyMonitoringExt::_tc_NameMapError
    };
  static ::CORBA::ULong const nexceptions = 2;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::CosNotifyChannelAdmin::ConsumerAdmin>::ret_val retval;
  TAO::SArg_Traits< ::CosNotifyChannelAdmin::InterFilterGroupOperator>::in_arg_val _tao_op;
  TAO::SArg_Traits< ::CORBA::Long>::out_arg_val _tao_id;
  TAO::SArg_Traits< char *>::in_arg_val _tao_name;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_op,
      &_tao_id,
      &_tao_name
    };
  
  static size_t const nargs = 4;

  POA_NotifyMonitoringExt::EventChannel * const impl =
    dynamic_cast<POA_NotifyMonitoringExt::EventChannel *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  named_new_for_consumers_EventChannel command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_NotifyMonitoringExt
{
  

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\upcall_command_ss.cpp:80

  class named_new_for_suppliers_EventChannel
    : public TAO::Upcall_Command
  {
  public:
    inline named_new_for_suppliers_EventChannel (
      POA_NotifyMonitoringExt::EventChannel * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::SupplierAdmin>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CosNotifyChannelAdmin::SupplierAdmin> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::InterFilterGroupOperator>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CosNotifyChannelAdmin::InterFilterGroupOperator> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CORBA::Long>::out_arg_type arg_2 =
        TAO::Portable_Server::get_out_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          2);
        
      TAO::SArg_Traits< char *>::in_arg_type arg_3 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          3);
        
      retval =
        this->servant_->named_new_for_suppliers (
          arg_1
          , arg_2
          , arg_3);
    }
  
  private:
    POA_NotifyMonitoringExt::EventChannel * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_ss.cpp:168

void POA_NotifyMonitoringExt::EventChannel::named_new_for_suppliers_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      NotifyMonitoringExt::_tc_NameAlreadyUsed,
      NotifyMonitoringExt::_tc_NameMapError
    };
  static ::CORBA::ULong const nexceptions = 2;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::CosNotifyChannelAdmin::SupplierAdmin>::ret_val retval;
  TAO::SArg_Traits< ::CosNotifyChannelAdmin::InterFilterGroupOperator>::in_arg_val _tao_op;
  TAO::SArg_Traits< ::CORBA::Long>::out_arg_val _tao_id;
  TAO::SArg_Traits< char *>::in_arg_val _tao_name;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_op,
      &_tao_id,
      &_tao_name
    };
  
  static size_t const nargs = 4;

  POA_NotifyMonitoringExt::EventChannel * const impl =
    dynamic_cast<POA_NotifyMonitoringExt::EventChannel *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  named_new_for_suppliers_EventChannel command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:163



::CORBA::Boolean POA_NotifyMonitoringExt::EventChannel::_is_a (const char* value)
{
  return
    (
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotification/QoSAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotification/AdminPropertiesAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosEventChannelAdmin/EventChannel:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyChannelAdmin/EventChannel:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:sandia.gov/NotifyMonitoringExt/EventChannel:1.0"
        ) == 0 ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_NotifyMonitoringExt::EventChannel::_interface_repository_id (void) const
{
  return "IDL:sandia.gov/NotifyMonitoringExt/EventChannel:1.0";
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:423

void POA_NotifyMonitoringExt::EventChannel::_dispatch (
  TAO_ServerRequest & req,
  TAO::Portable_Server::Servant_Upcall* servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:370

NotifyMonitoringExt::EventChannel *
POA_NotifyMonitoringExt::EventChannel::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();

  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();

  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0);
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();

  typedef ::NotifyMonitoringExt::EventChannel STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in ());
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_interface.cpp:1863

class TAO_NotifyMonitoringExt_EventChannelFactory_Perfect_Hash_OpTable
  : public TAO_Perfect_Hash_OpTable
{
private:
  unsigned int hash (const char *str, unsigned int len);

public:
  const TAO_operation_db_entry * lookup (const char *str, unsigned int len);
};

/* C++ code produced by gperf version 2.8 (ACE version) */
/* Command-line: ace_gperf -m -M -J -c -C -D -E -T -f 0 -F 0,0 -a -o -t -p -K opname -L C++ -Z TAO_NotifyMonitoringExt_EventChannelFactory_Perfect_Hash_OpTable -N lookup  */
unsigned int
TAO_NotifyMonitoringExt_EventChannelFactory_Perfect_Hash_OpTable::hash (const char *str, unsigned int len)
{
  static const unsigned char asso_values[] =
    {
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
     26, 26, 26, 26, 26,  0, 26,  0, 26,  5,
      0,  5, 26,  0, 26, 10, 26,  0,  0, 26,
     26, 26, 26, 26,  5,  5,  0,  5, 26, 26,
     26,  0, 26, 26, 26, 26, 26, 26,
    };
  return len + asso_values[static_cast<int>(str[len - 1])] + asso_values[static_cast<int>(str[0])];
}

const TAO_operation_db_entry *
TAO_NotifyMonitoringExt_EventChannelFactory_Perfect_Hash_OpTable::lookup (const char *str, unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 14,
      MIN_WORD_LENGTH = 5,
      MAX_WORD_LENGTH = 20,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 25,
      HASH_VALUE_RANGE = 21,
      DUPLICATES = 0,
      WORDLIST_SIZE = 19
    };

  static const TAO_operation_db_entry wordlist[] =
    {
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"_is_a", &TAO_ServantBase::_is_a_thru_poa_skel, 0},
      {"",0,0},
      {"destroy", &POA_NotifyExt::EventChannelFactory::destroy_skel, 0},
      {"",0,0},{"",0,0},
      {"_component", &TAO_ServantBase::_component_thru_poa_skel, 0},
      {"",0,0},{"",0,0},
      {"_non_existent", &TAO_ServantBase::_non_existent_thru_poa_skel, 0},
      {"_repository_id", &TAO_ServantBase::_repository_id_thru_poa_skel, 0},
      {"_interface", &TAO_ServantBase::_interface_skel, 0},
      {"",0,0},
      {"get_event_channel", &POA_CosNotifyChannelAdmin::EventChannelFactory::get_event_channel_skel, 0},
      {"save_topology", &POA_NotifyExt::EventChannelFactory::save_topology_skel, 0},
      {"create_channel", &POA_CosNotifyChannelAdmin::EventChannelFactory::create_channel_skel, 0},
      {"",0,0},
      {"get_all_channels", &POA_CosNotifyChannelAdmin::EventChannelFactory::get_all_channels_skel, 0},
      {"register_callback", &POA_NotifyExt::ReconnectionRegistry::register_callback_skel, 0},
      {"is_alive", &POA_NotifyExt::ReconnectionRegistry::is_alive_skel, 0},
      {"unregister_callback", &POA_NotifyExt::ReconnectionRegistry::unregister_callback_skel, 0},
      {"create_named_channel", &POA_NotifyMonitoringExt::EventChannelFactory::create_named_channel_skel, 0},
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          const char *s = wordlist[key].opname;

          if (*str == *s && !ACE_OS::strncmp (str + 1, s + 1, len - 1))
            return &wordlist[key];
        }
    }
  return 0;
}

static TAO_NotifyMonitoringExt_EventChannelFactory_Perfect_Hash_OpTable tao_NotifyMonitoringExt_EventChannelFactory_optable;

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:90

POA_NotifyMonitoringExt::EventChannelFactory::EventChannelFactory (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_NotifyMonitoringExt_EventChannelFactory_optable;
}

POA_NotifyMonitoringExt::EventChannelFactory::EventChannelFactory (const EventChannelFactory& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_CosNotifyChannelAdmin::EventChannelFactory (rhs),
    POA_NotifyExt::ReconnectionRegistry (rhs),
    POA_NotifyExt::EventChannelFactory (rhs)
{
}

POA_NotifyMonitoringExt::EventChannelFactory::~EventChannelFactory (void)
{
}

namespace POA_NotifyMonitoringExt
{
  

  // TAO_IDL - Generated from
  // c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\upcall_command_ss.cpp:80

  class create_named_channel_EventChannelFactory
    : public TAO::Upcall_Command
  {
  public:
    inline create_named_channel_EventChannelFactory (
      POA_NotifyMonitoringExt::EventChannelFactory * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CosNotifyChannelAdmin::EventChannel>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CosNotifyChannelAdmin::EventChannel> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CosNotification::QoSProperties>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CosNotification::QoSProperties> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CosNotification::AdminProperties>::in_arg_type arg_2 =
        TAO::Portable_Server::get_in_arg< ::CosNotification::AdminProperties> (
          this->operation_details_,
          this->args_,
          2);
        
      TAO::SArg_Traits< ::CORBA::Long>::out_arg_type arg_3 =
        TAO::Portable_Server::get_out_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          3);
        
      TAO::SArg_Traits< char *>::in_arg_type arg_4 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          4);
        
      retval =
        this->servant_->create_named_channel (
          arg_1
          , arg_2
          , arg_3
          , arg_4);
    }
  
  private:
    POA_NotifyMonitoringExt::EventChannelFactory * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_ss.cpp:168

void POA_NotifyMonitoringExt::EventChannelFactory::create_named_channel_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      CosNotification::_tc_UnsupportedQoS,
      CosNotification::_tc_UnsupportedAdmin,
      NotifyMonitoringExt::_tc_NameAlreadyUsed,
      NotifyMonitoringExt::_tc_NameMapError
    };
  static ::CORBA::ULong const nexceptions = 4;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::CosNotifyChannelAdmin::EventChannel>::ret_val retval;
  TAO::SArg_Traits< ::CosNotification::QoSProperties>::in_arg_val _tao_initial_qos;
  TAO::SArg_Traits< ::CosNotification::AdminProperties>::in_arg_val _tao_initial_admin;
  TAO::SArg_Traits< ::CORBA::Long>::out_arg_val _tao_id;
  TAO::SArg_Traits< char *>::in_arg_val _tao_name;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_initial_qos,
      &_tao_initial_admin,
      &_tao_id,
      &_tao_name
    };
  
  static size_t const nargs = 5;

  POA_NotifyMonitoringExt::EventChannelFactory * const impl =
    dynamic_cast<POA_NotifyMonitoringExt::EventChannelFactory *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  create_named_channel_EventChannelFactory command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:163



::CORBA::Boolean POA_NotifyMonitoringExt::EventChannelFactory::_is_a (const char* value)
{
  return
    (
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyChannelAdmin/EventChannelFactory:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:NotifyExt/ReconnectionRegistry:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:NotifyExt/EventChannelFactory:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:sandia.gov/NotifyMonitoringExt/EventChannelFactory:1.0"
        ) == 0 ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_NotifyMonitoringExt::EventChannelFactory::_interface_repository_id (void) const
{
  return "IDL:sandia.gov/NotifyMonitoringExt/EventChannelFactory:1.0";
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:423

void POA_NotifyMonitoringExt::EventChannelFactory::_dispatch (
  TAO_ServerRequest & req,
  TAO::Portable_Server::Servant_Upcall* servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// c:\private\datascience\neuralna_mreza\neuralnetwork\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ss.cpp:370

NotifyMonitoringExt::EventChannelFactory *
POA_NotifyMonitoringExt::EventChannelFactory::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();

  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();

  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0);
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();

  typedef ::NotifyMonitoringExt::EventChannelFactory STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in ());
}

#endif /* ifndef */

